parameters:
    app.frontend_url: '%env(FRONTEND_URL)%'
    app.mailer_from: '%env(MAILER_FROM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AuthService:
        arguments:
            $frontendUrl: '%app.frontend_url%'
            $mailerFrom: '%app.mailer_from%'
